name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_EDITORS: "True"
          SHOW_COMMIT: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          UPDATED_DATE_FORMAT: "%m/%d/%Y %H:%M:%S"
          SHOW_TOTAL_CODE_TIME: "True"
          SYMBOL_VERSION: 1
          TIME_RANGE: all_time
